# Generated by Django 2.2.5 on 2019-10-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191019_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='default_image_url',
            new_name='default_image',
        ),
    ]
