# 图形验证码有效期，单位：秒
IMAGE_CODE_REDIS_EXPIRES = 300

# 短信验证码有效期，单位：秒
SMS_CODE_REDIS_EXPIRES = 300

# 短信模板
SEND_SMS_TEMPLATE_ID = 1

# 60s内是否重复发送的标记
SEND_SMS_CODE_INTERVAL = 0

USER_ADDRESS_COUNTS_LIMIT = 20


GOODS_LIST_LIMIT = 5
CARTS_COOKIE_EXPIRES = 3600 * 12

ORDERS_LIST_LIMIT = 3